Add bot
campus-experts/discord-hackathon-template pull request #14
Opened 2021-05-18 02:09 UTC by endersonmenezes

I've already organized some hackathons here in Brazil, and this bot has always been useful to me to account for members' participation in a channel.

2021-07-21 04:42 UTC, juanpflores commented
Hi @endersonmenezes 👋🏼 
Would love to add this bot to the list! Could you solve the merge conflicts so we can merge it?

2021-07-21 04:45 UTC, juanpflores requested changes
Merge conflicts need to be solved before merging

2021-07-21 08:06 UTC, XynoxTheDev commented on README.md
>  | [Templae](https://github.com) | Template |
What's this is for?

2021-07-28 01:24 UTC, XynoxTheDev commented
@juanpflores There is no response in this PR and it has been a week, ig this PR should be closed and contributors can request to open it in the future!

2021-08-18 22:05 UTC, endersonmenezes commented on README.md
>  | [Templae](https://github.com) | Template |
Sorry i'm late. Its a bot for discord.

2021-08-18 22:06 UTC, endersonmenezes commented
You can close it, I'll see how the model is now and try to contribute.

2021-08-18 22:06 UTC, closed without merging